### PR TITLE
Add dynamic shortcuts

### LINKED ISSUE #44: support for minimalist launchers
**Feature description**

i'm using niagara. it only allows for 1 widget, for good reasons.

could you please add some option to either add application shortcuts (so each script would be like a web page shortcut) and or app action (like "termux new session")?

thanks for these amazing tools around termux!

### PR DESCRIPTION
**Pull request by fabian-thomas**
Closes #44
Closes termux/termux-app#1730

Current implementation:
Two new buttons in widget main view.
- Create button: adds all shortcuts as dynamic shortcuts. Those can then be used in minimalistic launchers. (Icons supported as well)
- Clear button: clears all shortcuts.

AOSP Android forces a limit of 10 shortcuts per app. One can change this limit with root permissions:
`su -c 'settings put global shortcut_manager_constants max_shortcuts=1000'`

Todo:
- [x] refactor/modularize code
- [x] add user feedback/logging
- [x] try to hide app name that gets displayed in front of shortcut name: probably not possible
- [x] add mention in readme (also on how to increase limit)
- [x] move those dynamic shortcuts to different folder than normal shortcuts (`~/.shortcuts`)
- [x] move FileFilter SHORTCUT_FILES_FILTER to enumerateShortcutFiles?

### CODE REVIEW

**Comment by fabian-thomas** [comment]
This PR is basically ready from my side. The last two points in the TODO above still need to be discussed.

**Comment by fabian-thomas** [comment]
1. Your code is much more readable and mine is actually wrong 😅. I will apply that change. To understand why it's wrong you need to know that the break condition in the for loop is actually evaluated in each iteration of the loop. But even if the condition would only be executed once in for loops vs. multiple times in while loops we would have no real performance difference since `ArrayList.size()` is `O(1)`. Take a look at the [openjdk implementation](https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/19fb8f93c59dfd791f62d41f332db9e306bc1422/src/java.base/share/classes/java/util/ArrayList.java#L283) of `ArrayList`.
2. The pinned and static shortcuts are those that have been used for a while now on the home screen. I only added the dynamic ones. I would say we do not need a remark on them in the readme since they are somewhat "normal" for android.

**Comment by agnostic-apollo** [comment]
Thanks for the pull request. Good work. I have made refactored the code to fix some issues and add improvements. It seems to be working fine on Android `11`, and without it on Android `7.0`. Nice idea on `ShortcutFile` and `ShortcutUtils` extraction, about time for that.

I have also changed the dynamic shortcuts directory to `~/.termux/widget/dynamic_shortcuts` since shouldn't just add all shortcuts in shortcuts directory as dynamic and shortcuts default directory will be moved to under `~/.termux/widget` in future from `~/.shortcuts`, so should move for this now.

Also in future, please remove unused imports when you move around code before committing, had to spent time figuring out which import got removed when and fixing the commits. Also use same case for commit messages as being used in repo.

I will merge this soon since need these changes for other work.

**Comment by fabian-thomas** [comment]
Nice, thanks for your work. 👍🏼 
Glad to see this finally coming to master.

**Comment by agnostic-apollo** [comment]
You are welcome. Any issues that occur can be fixed in `master`.

**Comment by ipcjs** [comment]
When will a new version be released that includes the feature?

**Comment by marbetschar** [comment]
Sorry for the necro bump - but I do have the same question: How/Where can we obtain a new version providing the dynamic_shortcuts feature?

**Comment by agnostic-apollo** [comment]
You can use github action builds for now, github/fdroid release will be done in a few days.

https://github.com/termux/termux-widget?tab=readme-ov-file#github

**Comment by marbetschar** [comment]
The build artifact is not installable on my device - it claims that the `*.apk` was built for a too old Android version. Waiting for the F-Droid release then.

FWIW: I get the same error (too old Android version) for Termux:Boot from F-Droid. Hoping its different for this then :crossed_fingers:

**Review by Bioharzard — COMMENTED** [review]
https://t.me/GenkiMinerBot/GenkiMiner?startapp=bvMkQVcr

**Comment by DHANAVATHgANESH** [comment]
Unable install to bootstrap

**Comment by DHANAVATHgANESH** [comment]
Unsafe app blocked

    Termux:Boot

This app was built for an older version of Android and doesn't include the latest privacy protections.

**Comment by twaik** [comment]
And you decided to report it in a random PR of different plugin (unrelated to `termux-boot`) repo in the same organisation, right?

**Pull request merged**
